### ISSUE TITLE
Reorder does not invalidate cache

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw.mobile#21]
When reordering in folder contents (object position in parent), the cache is not invalidated.

**Comment by jone** [comment]
This is hard to solve without slowing down generating the cache key:
The problem is that reorder does not update the modified timestamp and the when generating the cache key only the first 50 items, ordered by modified date, will be respected.
This means that even when we add the object position to the cache key we will not track reordered objects when they are not in the 50 last recently changed items in the startup query.

Therefore this is not easy to solve without making things very slow.

**Comment by jone** [comment]
I think this is fixed => to be test

**Comment by maethu** [comment]
I'm not able to reproduce this issue anymore.

**Comment by maethu** [comment]
Seems to be fixed.
