### ISSUE TITLE
Provide link to get to the current top level

### ISSUE THREAD

**Issue by bierik** [4teamwork/ftw.mobile#22]
Currently it's not possible to get to the top level tab navigation through the tabs

**Comment by jone** [comment]
If I understand you correctly, I think this can be achieved by clicking on the tab.

**Comment by bierik** [comment]
No I meant you can not get to the contentpage of the first level tabs by clicking on them

**Comment by jone** [comment]
This is partially fixed:
- When the level 1 node has no children, the page of level 1 is loaded on click.
- When the level 1 node has children, the navigation shows the children on click.

This covers our standard use cases.
