### ISSUE TITLE
Mobile navigation does not close in IE

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/ftw.mobile#40]
When using the latest version of `ftw.mobile` in IE, the mobile navigation can not be closed. It opens fine, the navigation per se also works without any problem, but if you want to close it again by clicking beside it (ride side) nothing will happen.

I think this is a problem with the pointer events, since it also doesn't change the cursor when hovering over the area on which the navigation can be closed.

**Comment by bierik** [comment]
@raphael-s I tested the issue with plonetheme.blueberry on IE11. I was not able to reproduce the described behavior. Could you give me more information.

**Comment by raphael-s** [comment]
This problem seems to be an edge case. It only occurs when `ftw.simplelayout` is active.
Since `ftw.simplelayout` doesn't work on mobile devices anyway, we don't need to fix this.
