### ISSUE TITLE
Mobile menu classes are not consistent when opening mobile menus

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/ftw.mobile#44]
While [openMenu](https://github.com/4teamwork/ftw.mobile/blob/master/ftw/mobile/js/simple-buttons.js#L29-L34) adds the class `open` to the `#ftw-mobile-menu` element, [slideIn](https://github.com/4teamwork/ftw.mobile/blob/master/ftw/mobile/js/simple-buttons.js#L55-L64) just adds the class `menu-open`.

The `slideIn` and `slideOut` functions are used for the mobile navigation, while `openMenu` and `closeMenu` are used for all other buttons. This is not consitent and should be changed.

Is there a reason for this behaviour?

cc @maethu

**Comment by bierik** [comment]
@raphael-s is this still an issue?

**Comment by raphael-s** [comment]
@bierik No, not anymore.
